Algoritmo "imprimeletras“
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Leia uma variável do tipo caractere e depois imprima cada
// uma de suas letras
var
palavra : caractere
tam,contador : inteiro

inicio
escreva ("Digite uma palavra: ")
leia(palavra)
tam <- compr(palavra)
para contador de 1 ate tam faca
escreval(copia(palavra,contador,1))
fimpara
fimalgoritmo